// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main(){	a[0] = "nx_us_space_assault_head_a";	a[1] = "nx_hero_charlie_head";	a[2] = "nx_us_secretservice_head_a";	a[3] = "nx_us_secretservice_head_b";	a[4] = "nx_us_secretservice_head_c";	a[5] = "nx_hero_vp_head";	return a;}
