// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "body_urban_civ_male_aa";
	a[1] = "body_urban_civ_male_ab";
	a[2] = "body_urban_civ_male_ac";
	a[3] = "body_urban_civ_male_ba";
	a[4] = "body_urban_civ_male_bb";
	a[5] = "body_urban_civ_male_bc";
	return a;
}
