// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main(){	a[0] = "nx_russian_head_a";	a[1] = "nx_russian_head_b";	a[2] = "nx_russian_head_c";	a[3] = "nx_russian_head_d";	a[4] = "nx_head_turks_army_a";	a[5] = "nx_head_turks_army_b";	return a;}
