// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "nx_china_space_assault_head_a";
	a[1] = "nx_china_space_assault_head_b";
	a[2] = "nx_china_space_assault_head_c";
	a[3] = "nx_china_space_assault_head_d";
	return a;
}
