// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main(){	a[0] = "nx_china_specops_head_a";	a[1] = "nx_china_specops_head_b";	a[2] = "nx_china_specops_head_c";	a[3] = "nx_china_specops_head_d";	return a;}
