// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	a[0] = "nx_china_space_assault_head_a_crack";
	a[1] = "nx_china_space_assault_head_b_crack";
	a[2] = "nx_china_space_assault_head_c_crack";
	a[3] = "nx_china_space_assault_head_d_crack";
	return a;
}
