// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
/*QUAKED actor_nx_ally_us_secretservice_agent2 (0.0 0.25 1.0) (-16 -16 0) (16 16 72) SPAWNER FORCESPAWN UNDELETABLE PERFECTENEMYINFO DONTSHAREENEMYINFO
defaultmdl="nx_us_secretservice_body_a"
"count" -- max AI to ever spawn from this spawner
SPAWNER -- makes this a spawner instead of a guy
FORCESPAWN -- will try to delete an AI if spawning fails from too many AI
UNDELETABLE -- this AI (or AI spawned from here) cannot be deleted to make room for FORCESPAWN guys
PERFECTENEMYINFO -- this AI when spawned will get a snapshot of perfect info about all enemies
DONTSHAREENEMYINFO -- do not get shared info about enemies at spawn time from teammates
*/
main()
{
	self.animTree = "";
	self.additionalAssets = "";
	self.team = "allies";
	self.type = "human";
	self.subclass = "regular";
	self.accuracy = 0.01;
	self.health = 1000;
	self.secondaryweapon = "";
	self.sidearm = "m9";
	self.grenadeWeapon = "fraggrenade";
	self.grenadeAmmo = 0;

	if ( isAI( self ) )
	{
		self setEngagementMinDist( 0.000000, 0.000000 );
		self setEngagementMaxDist( 0.000000, 0.000000 );
	}

	switch( codescripts\character::get_random_weapon(2) )
	{
	case 0:
		self.weapon = "ump55";
		break;
	case 1:
		self.weapon = "ump55_reflex";
		break;
	}

	character\nx_character_us_secretservice_b::main();
}

spawner()
{
	self setspawnerteam("allies");
}

precache()
{
	character\nx_character_us_secretservice_b::precache();

	precacheItem("ump55");
	precacheItem("ump55_reflex");
	precacheItem("m9");
	precacheItem("fraggrenade");
}
