// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_nx_chinese_lgv::main("nx_vehicle_chinese_lgv","nx_chinese_lgv");
	maps\_nx_chinese_skimmer::main( "nx_vehicle_chinese_skimmer" );
	maps\_nx_moving_platform_vh::main("nx_vehicle_moving_platform");
	maps\_nx_moving_platform_vh::main("nx_vehicle_moving_platform", "nx_moving_platform_ai_turret");
	maps\_nx_moving_platform_vh::main("nx_vehicle_moving_platform", "nx_moving_platform_enemy_ai_turret");
}
