// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\_nx_chinese_lgv::main("nx_vehicle_chinese_lgv","nx_chinese_lgv");
	maps\_nx_lunar_rover::main("nx_vehicle_lunar_rover","nx_lunar_rover");
}
