// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_city_civ_female_a");
	codescripts\character::attachHead( "alias_city_civ_female_heads", xmodelalias\alias_city_civ_female_heads::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("body_city_civ_female_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_city_civ_female_heads::main());
}
