// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{	
	self setModel("body_complete_mp_pmc_ai_temp");	
	self attach("head_complete_mp_pmc_ai_temp", "", true);	
	self.headModel = "head_complete_mp_pmc_ai_temp";
	self setViewmodel("viewhands_usmc");
	self.voice = "american";
}
precache()
{	
	precacheModel("body_complete_mp_pmc_ai_temp");	
	precacheModel("head_complete_mp_pmc_ai_temp");	
	precacheModel("viewhands_usmc");
}