// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_work_civ_male_d");
	self attach("hero_baseman_head", "", true);
	self.headModel = "hero_baseman_head";
	self.voice = "american";
}

precache()
{
	precacheModel("body_work_civ_male_d");
	precacheModel("hero_baseman_head");
}
