// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_us_specops_body_assault_a");
	codescripts\character::attachHead( "alias_nx_us_specops_heads", xmodelalias\alias_nx_us_specops_heads::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("nx_us_specops_body_assault_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_nx_us_specops_heads::main());
}
