// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_work_civ_male_d");
	self attach("nx_hero_charlie_head", "", true);
	self.headModel = "nx_hero_charlie_head";
	self.voice = "american";
}

precache()
{
	precacheModel("body_work_civ_male_d");
	precacheModel("nx_hero_charlie_head");
}
