// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_mexican_army_digital_body_shotgun_a");
	codescripts\character::attachHead( "alias_nx_mexican_army_heads", xmodelalias\alias_nx_mexican_army_heads::main() );
	self.voice = "mexican";
}

precache()
{
	precacheModel("nx_mexican_army_digital_body_shotgun_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_nx_mexican_army_heads::main());
}
