// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_us_secretservice_body_c");
	self attach("nx_us_secretservice_head_c", "", true);
	self.headModel = "nx_us_secretservice_head_c";
	self.voice = "american";
}

precache()
{
	precacheModel("nx_us_secretservice_body_c");
	precacheModel("nx_us_secretservice_head_c");
}
