// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_urban_civ_male_bb");
	self attach("nx_china_space_head_b_nohelm", "", true);
	self.headModel = "nx_china_space_head_b_nohelm";
	self.voice = "american";
}

precache()
{
	precacheModel("body_urban_civ_male_bb");
	precacheModel("nx_china_space_head_b_nohelm");
}
