// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_hero_baker_body_spec_pchute");
	self attach("nx_hero_baker_head", "", true);
	self.headModel = "nx_hero_baker_head";
	self.voice = "american";
}

precache()
{
	precacheModel("nx_hero_baker_body_spec_pchute");
	precacheModel("nx_hero_baker_head");
}
