// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_hero_vp_body_inj");
	self attach("nx_hero_vp_head_inj", "", true);
	self.headModel = "nx_hero_vp_head_inj";
	self.voice = "american";
}

precache()
{
	precacheModel("nx_hero_vp_body_inj");
	precacheModel("nx_hero_vp_head_inj");
}
