// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_us_secretservice_body_a");
	self attach("nx_hero_vp_head", "", true);
	self.headModel = "nx_hero_vp_head";
	self.voice = "american";
}

precache()
{
	precacheModel("nx_us_secretservice_body_a");
	precacheModel("nx_hero_vp_head");
}
