// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_hospital_doctor_body");
	self attach("nx_hospital_doctor_head", "", true);
	self.headModel = "nx_hospital_doctor_head";
	self.voice = "russian";
}

precache()
{
	precacheModel("nx_hospital_doctor_body");
	precacheModel("nx_hospital_doctor_head");
}
