// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_china_space_assault_body");
	codescripts\character::attachHead( "alias_china_space_heads_nohelm", xmodelalias\alias_china_space_heads_nohelm::main() );
	self.voice = "american";
}

precache()
{
	precacheModel("nx_china_space_assault_body");
	codescripts\character::precacheModelArray(xmodelalias\alias_china_space_heads_nohelm::main());
}
