// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_secret_service_assault_a");
	codescripts\character::attachHead( "alias_nx_ec_security_guard_heads", xmodelalias\alias_nx_ec_security_guard_heads::main() );
	self.voice = "indonesian";
}

precache()
{
	precacheModel("body_secret_service_assault_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_nx_ec_security_guard_heads::main());
}
