// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_hero_soap_socom");
	self attach("nx_hero_baker_head_delta", "", true);
	self.headModel = "nx_hero_baker_head_delta";
	self.voice = "american";
}

precache()
{
	precacheModel("body_hero_soap_socom");
	precacheModel("nx_hero_baker_head_delta");
}
