// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_hero_baker_body_spec");
	self attach("nx_hero_baker_head_phone", "", true);
	self.headModel = "nx_hero_baker_head_phone";
	self.voice = "american";
}

precache()
{
	precacheModel("nx_hero_baker_body_spec");
	precacheModel("nx_hero_baker_head_phone");
}
