// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("nx_civ_astronaut_body_complete_a");
	self.voice = "american";
}

precache()
{
	precacheModel("nx_civ_astronaut_body_complete_a");
}
