// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("china_army_body_assault_a");
	codescripts\character::attachHead( "alias_nx_china_army_heads", xmodelalias\alias_nx_china_army_heads::main() );
	self.voice = "arab";
}

precache()
{
	precacheModel("china_army_body_assault_a");
	codescripts\character::precacheModelArray(xmodelalias\alias_nx_china_army_heads::main());
}
