// this file is autogenerated, modifying parameters is ok, other lines will be removed.
main()
{
	maps\animated_models\foliage_tree_palm_bushy_1::main();
	maps\animated_models\foliage_tree_palm_bushy_3::main();
	maps\animated_models\highrise_fencetarp_01::main();
	maps\animated_models\highrise_fencetarp_09::main();
}